@php($value = fn (string $key, mixed $default = '') => old($key, $profile?->{$key} ?? $default))
<div class="grid gap-6 sm:grid-cols-2">
    @if (!$profile)<label class="block sm:col-span-2"><span class="font-semibold text-slate-800">Organization</span><select name="organization_id" class="mt-2 w-full rounded-xl border-slate-300">@foreach($organizations as $organization)<option value="{{ $organization->id }}" @selected(old('organization_id') == $organization->id)>{{ $organization->name }}</option>@endforeach</select></label>@endif
    <label class="block"><span class="font-semibold text-slate-800">Profile type</span><select name="type" class="mt-2 w-full rounded-xl border-slate-300">@foreach(['business','individual','employee','branch','restaurant','professional','freelancer'] as $type)<option value="{{ $type }}" @selected($value('type','business') === $type)>{{ ucfirst($type) }}</option>@endforeach</select></label>
    <label class="block"><span class="font-semibold text-slate-800">Preferred language</span><select name="preferred_language" class="mt-2 w-full rounded-xl border-slate-300"><option value="en" @selected($value('preferred_language','en') === 'en')>English</option><option value="ar" @selected($value('preferred_language') === 'ar')>العربية</option></select></label>
    <label class="block"><span class="font-semibold text-slate-800">Name</span><input name="name" value="{{ $value('name') }}" required class="mt-2 w-full rounded-xl border-slate-300"></label>
    <label class="block"><span class="font-semibold text-slate-800">Public URL slug</span><input name="slug" value="{{ $value('slug') }}" required pattern="[A-Za-z0-9_-]+" class="mt-2 w-full rounded-xl border-slate-300"></label>
    <label class="block"><span class="font-semibold text-slate-800">Company</span><input name="company_name" value="{{ $value('company_name') }}" class="mt-2 w-full rounded-xl border-slate-300"></label>
    <label class="block"><span class="font-semibold text-slate-800">Designation</span><input name="designation" value="{{ $value('designation') }}" class="mt-2 w-full rounded-xl border-slate-300"></label>
    <label class="block"><span class="font-semibold text-slate-800">Category</span><input name="category" value="{{ $value('category') }}" class="mt-2 w-full rounded-xl border-slate-300"></label>
    <label class="block"><span class="font-semibold text-slate-800">Tagline</span><input name="tagline" value="{{ $value('tagline') }}" class="mt-2 w-full rounded-xl border-slate-300"></label>
    <label class="block sm:col-span-2"><span class="font-semibold text-slate-800">About</span><textarea name="about" rows="6" class="mt-2 w-full rounded-xl border-slate-300">{{ $value('about') }}</textarea></label>
    @if ($profile)<label class="block"><span class="font-semibold text-slate-800">Publishing status</span><select name="status" class="mt-2 w-full rounded-xl border-slate-300"><option value="draft" @selected($value('status') === 'draft')>Draft</option><option value="pending_approval" @selected($value('status') === 'pending_approval')>Submit for approval</option><option value="published" @selected($value('status') === 'published')>Published</option></select></label>@endif
</div>
@if ($errors->any())<div class="mt-6 rounded-xl border border-red-200 bg-red-50 p-4 text-red-800"><ul class="list-disc pl-5">@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif
